Repository Soen341-FrameNotWork/Framenotwork_SOEN341_Project_F24, pull requests merged in 2024-09, with the labels that each got.

#8 Added Baseline backend code with Nextauth and database credentials
  .DS_Store
  MySQL scripts/test.sql
  peer-assessment-app/app/api/auth/[...nextauth]/route.ts
  peer-assessment-app/app/login/SignIn.tsx
  peer-assessment-app/lib/db.ts
  peer-assessment-app/next.config.mjs
  peer-assessment-app/package-lock.json
  peer-assessment-app/package.json
  peer-assessment-app/tsconfig.json
Labels: help wanted, good first issue

#10 Added file for Meeting 1
  Meeting Minutes/FrameNotWork_Sprint1_Meeting1_12-09-2024
Labels: documentation

#9 Updated README.md
  README.md
Labels: documentation, good first issue

#11 SignIn and SignUp are working
  MySQL scripts/database.sql
  peer-assessment-app/.eslintrc.json
  peer-assessment-app/.vscode/launch.json
  peer-assessment-app/app/Instructor/page.tsx
  peer-assessment-app/app/Student/page.tsx
  peer-assessment-app/app/api/auth/[...nextauth]/route.ts
  peer-assessment-app/app/api/register/route.ts
  peer-assessment-app/app/instructor/page.tsx
  peer-assessment-app/app/login/SignIn.tsx
  peer-assessment-app/app/login/Signup.tsx
  peer-assessment-app/app/login/student_instructor_toggle.tsx
  peer-assessment-app/app/student/page.tsx
  peer-assessment-app/launch.json
  peer-assessment-app/lib/db.ts
  peer-assessment-app/next.config.mjs
Labels: enhancement

#12 Added files for Meeting 2-5
  Meeting Minutes/FrameNotWork_Sprint1_Meeting1_12-09-2024
  Meeting Minutes/FrameNotWork_Sprint1_Meeting2_15-09-2024
  Meeting Minutes/FrameNotWork_Sprint1_Meeting3_17-09-2024
  Meeting Minutes/FrameNotWork_Sprint1_Meeting4_19-09-2024
  Meeting Minutes/FrameNotWork_Sprint1_Meeting5_26-09-2024
Labels: documentation

#17 Updated README.md
  README.md
Labels: documentation

#23 Update README.md
  README.md
Labels: enhancement

#24 Fix Hydration error
  peer-assessment-app/app/Instructor/ListOfStudents/page.tsx
  peer-assessment-app/app/Instructor/components/Sidebar.tsx
  peer-assessment-app/app/Instructor/components/StudentList.tsx
  peer-assessment-app/app/Instructor/components/style.css
  peer-assessment-app/app/Instructor/page.tsx
  peer-assessment-app/app/Student/page.tsx
  peer-assessment-app/app/components/AccountMenu.tsx
  peer-assessment-app/app/components/Course.tsx
  peer-assessment-app/app/components/LeftSidebar.tsx
  peer-assessment-app/app/components/Navbar.tsx
  peer-assessment-app/app/components/StudentList.tsx
  peer-assessment-app/package-lock.json
Labels: bug

#25 Create FrameNotWork_Sprint1_Meeting6_29-09-2024
  Meeting Minutes/FrameNotWork_Sprint1_Meeting6_29-09-2024
Labels: documentation
